#  docker compose --env-file .env.x up

services:
  project:
    env_file:
      - "${ENV_FILE}"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_FILE: "${ENV_FILE}"
    volumes:
      - ./io:/app/io
    ports:
      - "${UVICORN_SERVER__PORT}:${UVICORN_SERVER__PORT}"
    depends_on:
      - db
    restart: on-failure

