services:
  dms:
    image: dms_api
    environment:
      # [ GENERAL ]
      GENERAL__IS_PRODUCTION: ${GENERAL__IS_PRODUCTION}
      GENERAL__APPLICATION_NAME: ${GENERAL__APPLICATION_NAME}
      GENERAL__PYTHONIC__APPLICATION_NAME: ${GENERAL__PYTHONIC__APPLICATION_NAME}
      GENERAL__APPLICATION_DESCRIPTION: ${GENERAL__APPLICATION_DESCRIPTION}
      GENERAL__APPLICATION_VERSION: ${GENERAL__APPLICATION_VERSION}

      # [ UVICORN_SERVER ]
      UVICORN_SERVER__APP: ${UVICORN_SERVER__APP}
      UVICORN_SERVER__HOST: ${UVICORN_SERVER__HOST}
      UVICORN_SERVER__PORT: ${UVICORN_SERVER__PORT}
      UVICORN_SERVER__LOG_LEVEL: ${UVICORN_SERVER__LOG_LEVEL}
      UVICORN_SERVER__PROXY_HEADERS: ${UVICORN_SERVER__PROXY_HEADERS}
      UVICORN_SERVER__FORWARDED_ALLOW_IPS: ${UVICORN_SERVER__FORWARDED_ALLOW_IPS}
      UVICORN_SERVER__RELOAD: ${UVICORN_SERVER__RELOAD}
      UVICORN_SERVER__LOOP: ${UVICORN_SERVER__LOOP}
      UVICORN_SERVER__WORKERS: ${UVICORN_SERVER__WORKERS}
      UVICORN_SERVER__SERVER_HEADER: ${UVICORN_SERVER__SERVER_HEADER}

      # [ LOGGING ]
      LOGGING__NAME: ${LOGGING__NAME}
      LOGGING__LEVEL: ${LOGGING__LEVEL}
      LOGGING__HANDLERS: ${LOGGING__HANDLERS}
      LOGGING__FORMAT: ${LOGGING__FORMAT}
      # Inputs of TimedRotatingFileHandler
      LOGGING__TIMED_ROTATING_FILE_HANDLER__FILENAME: ${LOGGING__TIMED_ROTATING_FILE_HANDLER__FILENAME}
      LOGGING__TIMED_ROTATING_FILE_HANDLER__WHEN: ${LOGGING__TIMED_ROTATING_FILE_HANDLER__WHEN}
      LOGGING__TIMED_ROTATING_FILE_HANDLER__INTERVAL: ${LOGGING__TIMED_ROTATING_FILE_HANDLER__INTERVAL}
      LOGGING__TIMED_ROTATING_FILE_HANDLER__BACKUP_COUNT: ${LOGGING__TIMED_ROTATING_FILE_HANDLER__BACKUP_COUNT}
      LOGGING__TIMED_ROTATING_FILE_HANDLER__ENCODING: ${LOGGING__TIMED_ROTATING_FILE_HANDLER__ENCODING}
      LOGGING__TIMED_ROTATING_FILE_HANDLER__DELAY: ${LOGGING__TIMED_ROTATING_FILE_HANDLER__DELAY}
      LOGGING__TIMED_ROTATING_FILE_HANDLER__UTC: ${LOGGING__TIMED_ROTATING_FILE_HANDLER__UTC}
      LOGGING__TIMED_ROTATING_FILE_HANDLER__AT_TIME: ${LOGGING__TIMED_ROTATING_FILE_HANDLER__AT_TIME}
      LOGGING__TIMED_ROTATING_FILE_HANDLER__ERRORS: ${LOGGING__TIMED_ROTATING_FILE_HANDLER__ERRORS}
      # Inputs of SysLogHandler
      LOGGING__SYSLOG_HANDLER__ADDRESS_HOST: ${LOGGING__SYSLOG_HANDLER__ADDRESS_HOST}
      LOGGING__SYSLOG_HANDLER__ADDRESS_PORT: ${LOGGING__SYSLOG_HANDLER__ADDRESS_PORT}
      LOGGING__SYSLOG_HANDLER__FACILITY: ${LOGGING__SYSLOG_HANDLER__FACILITY}
      LOGGING__SYSLOG_HANDLER__SOCKTYPE: ${LOGGING__SYSLOG_HANDLER__SOCKTYPE}
      # Inputs of StreamHandler
      LOGGING__STREAM_HANDLER__STREAM: ${LOGGING__STREAM_HANDLER__STREAM}

      # [MONGODB]
      MONGODB__HOST: db
      MONGODB__PORT: ${MONGODB__PORT}
      MONGODB__DATABASE: ${MONGODB__DATABASE}
      MONGODB__USERNAME: ${MONGODB__USERNAME}
      MONGODB__PASSWORD: ${MONGODB__PASSWORD}
      MONGODB__AUTHDB: ${MONGODB__AUTHDB}

      # [MONGODB_TEST]
      MONGODB_TEST__HOST: db
      MONGODB_TEST__PORT: ${MONGODB_TEST__PORT}
      MONGODB_TEST__DATABASE: ${MONGODB_TEST__DATABASE}
      MONGODB_TEST__USERNAME: ${MONGODB_TEST__USERNAME}
      MONGODB_TEST__PASSWORD: ${MONGODB_TEST__PASSWORD}
      MONGODB_TEST__AUTHDB: ${MONGODB_TEST__AUTHDB}

      # [PAGINATION]
      PAGINATION__PAGE_SIZE: ${PAGINATION__PAGE_SIZE}

      # [REGEX]
      REGEX__PHONE_NUMBER: ${REGEX__PHONE_NUMBER}
      REGEX__EMAIL: ${REGEX__EMAIL}
      REGEX__LANDLINE: ${REGEX__LANDLINE}
      REGEX__NATIONAL_ID: ${REGEX__NATIONAL_ID}
      REGEX__BASE64: ${REGEX__BASE64}

      # [OTP]
      OTP__RESEND_LOCK_DURATION_IN_SECOND: ${OTP__RESEND_LOCK_DURATION_IN_SECOND}
      OTP__VALIDITY_PERIOD_IN_SECONDS: ${OTP__VALIDITY_PERIOD_IN_SECONDS}
      OTP__NUMBER_OF_CHARACTERS: ${OTP__NUMBER_OF_CHARACTERS}
      OTP__ALLOWED_CHARACTER: ${OTP__ALLOWED_CHARACTER}

      # [TOKEN]
      TOKEN__SECRET_KEY: ${TOKEN__SECRET_KEY}
      TOKEN__HEADER_KEY_NAME: ${TOKEN__HEADER_KEY_NAME}
      TOKEN__VALIDITY_PERIOD_IN_DAYS: ${TOKEN__VALIDITY_PERIOD_IN_DAYS}
      TOKEN__ALGORITHM: ${TOKEN__ALGORITHM}

      # [PASSWORD]
      PASSWORD__MINIMUM_LENGTH: ${PASSWORD__MINIMUM_LENGTH}
      PASSWORD__SALT: ${PASSWORD__SALT}

      # [GZIP_MIDDLEWARE]
      GZIP_MIDDLEWARE__MINIMUM_SIZE_IN_BYTE: ${GZIP_MIDDLEWARE__MINIMUM_SIZE_IN_BYTE}

      # [CACHE]
      CACHE__CACHE_FOR_DB_ACTIONS: ${CACHE__CACHE_FOR_DB_ACTIONS}
      CACHE__CACHE_FOR_ROUTERS: ${CACHE__CACHE_FOR_ROUTERS}

      # [MINIO]
      MINIO__HOST: minio
      MINIO__PORT: ${MINIO__PORT}
      MINIO__SERVER_ACCESS_KEY: ${MINIO__SERVER_ACCESS_KEY}
      MINIO__SERVER_SECRET_KEY: ${MINIO__SERVER_SECRET_KEY}
      MINIO__SERVER_ADDRESS_FOR_CLIENT: http://dms.min0.apidar.com
      MINIO__SCHEDULER_INTERVAL_FOR_DELETE_USELESS_OBJECTS_IN_DAYS: ${MINIO__SCHEDULER_INTERVAL_FOR_DELETE_USELESS_OBJECTS_IN_DAYS}
      MINIO__EXPIRATION_DURATION_FOR_TEMPORARY_URLS_IN_HOURS: ${MINIO__EXPIRATION_DURATION_FOR_TEMPORARY_URLS_IN_HOURS}

    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    ports:
      - "${UVICORN_SERVER__PORT}:${UVICORN_SERVER__PORT}"
    depends_on:
      - db
      - minio

  db:
    image: mongo:7.0.8-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB__USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB__PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB__DATABASE}
    ports:
      - "${MONGODB__PORT}:${MONGODB__PORT}"
    volumes:
      - db-data:/data/db
  #      - ./docker_volumes/mongodb:/data/db

  minio:
    image: bitnami/minio:2024.5.1
    environment:
      MINIO_ROOT_USER: ${MINIO__ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO__ROOT_PASSWORD}
      MINIO_API_PORT_NUMBER: ${MINIO__API_PORT_NUMBER}
      MINIO_CONSOLE_PORT_NUMBER: ${MINIO__CONSOLE_PORT_NUMBER}
    ports:
      - '${MINIO__API_PORT_NUMBER}:${MINIO__API_PORT_NUMBER}'
      - '${MINIO__CONSOLE_PORT_NUMBER}:${MINIO__CONSOLE_PORT_NUMBER}'
    volumes:
      - minio-data:/bitnami/minio/data
#      - ./docker_volumes/minio:/bitnami/minio/data

volumes:
  db-data: ~
  minio-data: ~
