from ....setting import SETTINGS
#
# VARIABLE_PATH_V1_ADMIN_PREFIX = '/api/v1/admin/'
# VARIABLE_PATH_V1_CLIENT_PREFIX = '/api/v1/'
# VARIABLE_TAG_ADMIN = 'Admin - '
# VARIABLE_TAG_CLIENT = 'Client - '
# VARIABLE_TAG_CLIENT_AND_ADMIN = 'Client & Admin - '
#
# VARIABLE_S3_PROFILE_DIRECTORY_NAME = 'profile'
# #
# VARIABLE_TOKEN_SECRET_KEY = SETTINGS.TOKEN.SECRET_KEY
# VARIABLE_CACHE_FOR_DB_ACTIONS = SETTINGS.CACHE.CACHE_FOR_DB_ACTIONS
# VARIABLE_CACHE_FOR_ROUTERS = SETTINGS.CACHE.CACHE_FOR_ROUTERS
# VARIABLE_DEFAULT_PAGE_SIZE = SETTINGS.PAGINATION.PAGE_SIZE
# VARIABLE_PASSWORD_MINIMUM_LENGTH = SETTINGS.PASSWORD.MINIMUM_LENGTH
# VARIABLE_REGEX_PHONE_NUMBER = SETTINGS.REGEX.PHONE_NUMBER
# VARIABLE_REGEX_LANDLINE = SETTINGS.REGEX.LANDLINE
# VARIABLE_REGEX_EMAIL = SETTINGS.REGEX.EMAIL
# VARIABLE_REGEX_NATIONAL_ID = SETTINGS.REGEX.NATIONAL_ID
# VARIABLE_REGEX_BASE64 = SETTINGS.REGEX.BASE64
# VARIABLE_OTP_NUMBER_OF_CHARACTERS = SETTINGS.OTP.NUMBER_OF_CHARACTERS
# VARIABLE_OTP_ALLOWED_CHARACTERS = SETTINGS.OTP.ALLOWED_CHARACTER
#
# VARIABLE_KAVEH_NEGAR_API_KEY = SETTINGS.KAVEH_NEGAR.API_KEY
# VARIABLE_KAVEH_NEGAR_TEMPLATE_NAME = SETTINGS.KAVEH_NEGAR.TEMPLATE_NAME
#
#
# VARIABLE_OTP_REGEX_PATTERN = f'^[{VARIABLE_OTP_ALLOWED_CHARACTERS}]{{{VARIABLE_OTP_NUMBER_OF_CHARACTERS}}}$'
#
# VARIABLE_MINIO_SERVER_ADDRESS_FOR_CLIENT = SETTINGS.MINIO.SERVER_ADDRESS_FOR_CLIENT
# VARIABLE_MINIO_SCHEDULER_INTERVAL_FOR_DELETE_USELESS_OBJECTS_IN_DAYS = \
#     SETTINGS.MINIO.SCHEDULER_INTERVAL_FOR_DELETE_USELESS_OBJECTS_IN_DAYS
# VARIABLE_MINIO_EXPIRATION_DURATION_FOR_TEMPORARY_URLS_IN_SECOND = \
#     SETTINGS.MINIO.EXPIRATION_DURATION_FOR_TEMPORARY_URLS_IN_HOURS * 60 * 60
# VARIABLE_DATASET_WEBPAGE_ADDRESS = SETTINGS.DATASET.WEBPAGE_ADDRESS
#
# VARIABLE_REGEX_DATASET_LINK = f"^{VARIABLE_DATASET_WEBPAGE_ADDRESS}[0-9]+$"
# VARIABLE_DATASET_LINK_MIN_LENGTH = len(VARIABLE_DATASET_WEBPAGE_ADDRESS) + 1
#
# VARIABLE_USER_SECRET_KEY = SETTINGS.USER.SECRET_KEY
